Repository DevOps-MBSE/aac-rest-api, pull requests merged in 2024-07, with the labels that each got.

#17 Update api tests
  .github/workflows/python-cross-platform-support.yml
  .github/workflows/python-test-python-version.yml
  .gitpod.yml
  docs/source/conf.py
  legacy/__init__.py
  legacy/aac_rest_api_impl.py
  legacy/aac_rest_app.py
  legacy/models/__init__.py
  legacy/models/command_model.py
  legacy/models/definition_model.py
  legacy/models/file_model.py
  legacy/test_rest_api.py
  python/pyproject.toml
  python/secure_install/install_scripts/install_aac_air_gap.bash
  python/secure_install/install_scripts/install_aac_air_gap.bat
  python/secure_install/install_scripts/install_aac_verified_index.bash
  python/secure_install/install_scripts/install_aac_verified_index.bat
  python/secure_install/pipeline_scripts/create_install_archive.bash
  python/secure_install/pipeline_scripts/create_install_archive.bat
  python/src/rest_api/__init__.py
  python/src/rest_api/aac_rest_app.py
  python/src/rest_api/models/definition_model.py
  python/src/rest_api/rest_api_impl.py
  python/tests/calc/model/MathFunction.yaml
  python/tests/calc/model/MathRequest.yaml
  python/tests/calc/model/MathResponse.yaml
  python/tests/calc/model/calculator.yaml
  python/tests/calc/model/mathlogger.yaml
  python/tests/calc/model/mathmessagehandler.yaml
  python/tests/calc/spec/Add_SRS.yaml
  python/tests/calc/spec/Calculator_IRS.yaml
  python/tests/calc/spec/Calculator_SystemSpec.yaml
  python/tests/calc/spec/ComplexMath_PIDS.yaml
  python/tests/calc/spec/Divide_SRS.yaml
  python/tests/calc/spec/IntermediateMath_PIDS.yaml
  python/tests/calc/spec/Multiply_SRS.yaml
  python/tests/calc/spec/Power_SRS.yaml
  python/tests/calc/spec/SimpleMath_PIDS.yaml
  python/tests/calc/spec/SquareRoot_SRS.yaml
  python/tests/calc/spec/Subtract_SRS.yaml
  python/tests/rest_api/test_rest_api.py
  python/tox.ini
Labels: added

#18 Update gen-openapi-spec
  python/pyproject.toml
  python/src/rest_api/rest_api_impl.py
  python/tests/rest_api/test_rest_api.py
Labels: added

#19 Documentation
  docs/source/favicon.ico
  docs/source/images/openapi.png
  docs/source/index.rst
  docs/source/project_documentation/home_page_index.rst
  docs/source/project_documentation/rest-api.md
  python/pyproject.toml
  python/src/rest_api/rest_api_impl.py
Labels: documentation, added

#20 added sphinx workflow
  .github/workflows/sphinx.yml
Labels: added

#21 added pypi distribution
  .github/workflows/main-branch.yml
  .github/workflows/python-build-and-lint.yml
  python/pyproject.toml
Labels: added

#22 changed needs entry to build_python_artifacts
  .github/workflows/main-branch.yml
  python/pyproject.toml
Labels: added

#23 PyPi Deployment Artifact Path
  .github/workflows/main-branch.yml
  python/pyproject.toml
Labels: changed

#24 Download Artifact Version
  .github/workflows/main-branch.yml
  python/pyproject.toml
Labels: changed
